### ISSUE TITLE
Proxy is enabled if you make a non-Registry site proxy through a popup

### ISSUE THREAD

**Issue by Erghel** [roskomsvoboda/censortracker#498] opened 2022-10-22 18:27 UTC
https://user-images.githubusercontent.com/88831850/197356900-6d057a3e-0158-4dfc-9cad-3de8a114c4a3.mp4

**Comment by lk-geimfari** [comment] 2022-10-23 09:08
It's not a bug but a feature. I'm closing this one.

**Closed by lk-geimfari** 2022-10-23 09:08 UTC
